# Generated by Django 5.2 on 2025-04-26 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0003_streamingplatform_watchlist_delete_movie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamingplatform',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='imdb_app.streamingplatform'),
        ),
    ]
